# Generated by Django 3.1.3 on 2021-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=4000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='items_pics')),
            ],
        ),
    ]
